version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SONGS_LIBRARY_API=http://localhost:3000
    environment:
      - VITE_SONGS_LIBRARY_API=http://localhost:3000
    ports:
      - "5171:80" # Map port 3000 on the host to port 80 in the container
    restart: always
